#!/usr/bin/env python3
"""
Claude PR Review Agent - Reviews GitHub PRs and generates structured feedback.
Usage: claude-review --pr https://github.com/owner/repo/pull/123
"""
import subprocess
import sys
import json
import re
import argparse
from pathlib import Path

def fetch_pr_diff(pr_url: str) -> dict:
    """Fetch PR data and diff from GitHub."""
    # Parse PR URL
    match = re.match(r"https?://github\.com/([^/]+)/([^/]+)/pull/(\d+)", pr_url)
    if not match:
        raise ValueError(f"Invalid PR URL: {pr_url}")
    
    owner, repo, pr_num = match.groups()
    
    # Get PR info
    result = subprocess.run(
        ["gh", "pr", "view", pr_num, "--repo", f"{owner}/{repo}", "--json", "title,body,additions,deletions,changedFiles,files,author"],
        capture_output=True, text=True, timeout=30
    )
    if result.returncode != 0:
        raise Exception(f"Failed to fetch PR: {result.stderr}")
    
    pr_info = json.loads(result.stdout)
    
    # Get diff
    result2 = subprocess.run(
        ["gh", "pr", "diff", pr_num, "--repo", f"{owner}/{repo}"],
        capture_output=True, text=True, timeout=30
    )
    diff = result2.stdout if result2.returncode == 0 else ""
    
    return {
        "url": pr_url,
        "owner": owner,
        "repo": repo,
        "number": int(pr_num),
        "title": pr_info.get("title", ""),
        "body": pr_info.get("body", ""),
        "additions": pr_info.get("additions", 0),
        "deletions": pr_info.get("deletions", 0),
        "changed_files": pr_info.get("changedFiles", 0),
        "files": pr_info.get("files", []),
        "author": pr_info.get("author", {}).get("login", "unknown"),
        "diff": diff,
    }

def analyze_pr(pr_data: dict) -> dict:
    """Analyze PR and generate review."""
    diff = pr_data["diff"]
    files = pr_data["files"]
    
    # Identify risks
    risks = []
    if pr_data["deletions"] > pr_data["additions"] * 2:
        risks.append("Large number of deletions relative to additions")
    if pr_data["changed_files"] > 20:
        risks.append("Large PR with many files changed")
    
    # Check for dangerous patterns
    dangerous_patterns = [
        (r"rm\s+-rf", "Recursive file deletion"),
        (r"DROP\s+TABLE", "Database table drop"),
        (r"git\s+push.*--force", "Force push"),
        (r"password|secret|key|token", "Potential secret exposure"),
        (r"eval\s*\(", "Use of eval()"),
        (r"exec\s*\(", "Use of exec()"),
    ]
    
    for pattern, reason in dangerous_patterns:
        if re.search(pattern, diff, re.IGNORECASE):
            risks.append(f"Detected: {reason}")
    
    # Identify improvements
    suggestions = []
    if not any("test" in f.get("path", "").lower() for f in files):
        suggestions.append("Consider adding tests for new functionality")
    if pr_data["changed_files"] > 10:
        suggestions.append("Consider breaking this into smaller PRs")
    
    # Check for TODO/FIXME
    if "TODO" in diff or "FIXME" in diff:
        suggestions.append("Contains TODO/FIXME comments - review before merging")
    
    # Calculate confidence
    if len(risks) == 0 and pr_data["changed_files"] <= 5:
        confidence = "High"
    elif len(risks) <= 2:
        confidence = "Medium"
    else:
        confidence = "Low"
    
    # Generate summary
    summary = f"This PR modifies {pr_data['changed_files']} file(s) with +{pr_data['additions']}/-{pr_data['deletions']} lines."
    if pr_data["body"]:
        summary += f" Description: {pr_data['body'][:200]}"
    
    return {
        "summary": summary,
        "risks": risks if risks else ["No significant risks identified"],
        "suggestions": suggestions if suggestions else ["Looks good!"],
        "confidence": confidence,
    }

def format_review(review: dict, pr_data: dict) -> str:
    """Format review as structured Markdown."""
    lines = []
    lines.append("## 🤖 Automated PR Review")
    lines.append("")
    lines.append("### Summary")
    lines.append(review["summary"])
    lines.append("")
    lines.append("### Risks")
    for risk in review["risks"]:
        lines.append(f"- ⚠️ {risk}")
    lines.append("")
    lines.append("### Suggestions")
    for suggestion in review["suggestions"]:
        lines.append(f"- 💡 {suggestion}")
    lines.append("")
    lines.append(f"### Confidence: {review['confidence']}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Claude PR Review Agent*")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="Review a GitHub PR")
    parser.add_argument("--pr", required=True, help="GitHub PR URL")
    parser.add_argument("--output", help="Output file (default: stdout)")
    args = parser.parse_args()
    
    try:
        pr_data = fetch_pr_diff(args.pr)
        review = analyze_pr(pr_data)
        review_md = format_review(review, pr_data)
        
        if args.output:
            Path(args.output).write_text(review_md)
            print(f"Review written to {args.output}")
        else:
            print(review_md)
        
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())
